currentSpeed: 0.0
dropsAmount: 0
pusher: Сброс всех
rotDir: Против часовой
rotationAmount: 0
sessionFlag: false
startFlag: false
targetSpeed: 5.0
vacPos1: 2
vacPos2: 6
vaccinationAmount1: 0
vaccinationAmount2: 0
